require "julian.options"
require "julian.keymaps"
require "julian.plugins"
require "julian.colorscheme"
require "julian.cmp"
require "julian.lsp"
require "julian.telescope"
require "julian.treesitter"
require "julian.autopairs"
require "julian.comment"
require "julian.gitsigns"
require "julian.nvim-tree"
require "julian.bufferline"
require "julian.lualine"
-- require "julian.toggleterm"
-- require "julian.project"
require "julian.impatient"
require "julian.alpha"
require "julian.illuminate"
require "julian.autocommands"
require "julian.indentline"
-- require "julian.copilot"
